version: "3.9"

services:
  backend:
    build: ./inventory_forecasting_backend
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://host.docker.internal:3306/inventory_forecasting_db
      DB_USERNAME: root
      DB_PASSWORD: Vasanth@04

  frontend:
    build: ./inventory-ui-pro
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
